Mongo:
  image: mongo
  container_name: mongoc
  restart: always
  volumes:
    - /srv/docker/mongo/datadir:/data/db

Redis:
  image: redis
    restart: always
  container_name: redisc

IJust:
  image: ijust
  container_name: ijustc
  restart: always
  links:
    - Mongo
    - Redis
  volumes:
    - /var/www/ijust:/var/www/ijust
    - /tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock
